websocket-server:
  base-wss-url:
    ws://localhost:8082
  base-http-url:
    http://localhost:8082

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: websocket_route
          uri: ${websocket-server.base-wss-url}
          predicates:
            - Path=/ws/connect/**
          filters:
            - RewritePath=/ws/connect/,/ws/
          metadata:
            auth: test-auth
        - id: http_route
          uri: ${websocket-server.base-http-url}
          predicates:
            - Path=/ws/test-http/**
          filters:
            - RewritePath=/ws/test-http/,/test/
          metadata:
            auth: none

server:
  port: 8081