websocket-server:
  base-wss-url:
    ws://localhost:8082
  base-http-url:
    http://localhost:8082

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: websocket_route
          uri: ${websocket-server.base-wss-url}
          predicates:
            - Path=/ws/**
        #          predicates:
        #            - Path=/ws/connect/**
        #          filters:
        #            - RewritePath=/ws/connect/,/ws/
        - id: http_route
          uri: ${websocket-server.base-http-url}
          predicates:
            - Path=/test/**
#          predicates:
#            - Path=/ws/test-http/**
#          filters:
#            - RewritePath=/ws/test-http/,/test/

server:
  port: 8081